apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubedis-dev
  namespace: argocd
spec:
  project: kubedis-dev

  source:
    repoURL: https://github.com/yenlianglai/KubeDIS.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
