apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: testing
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Testing Project Group
  # Allow manifests to deploy from any Git repos
  sourceRepos:
    - 'https://github.com/yenlianglai/KubeDIS.git'
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
    - namespace: testing
      server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Service
    - group: 'apps'
      kind: Deployment
