apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app
  namespace: argocd
spec:
  project: testing

  source:
    repoURL: https://github.com/yenlianglai/KubeDIS.git
    targetRevision: HEAD
    path: testing/app
  destination:
    server: https://kubernetes.default.svc
    namespace: testing

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
