name: Deploy Images to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  workflow_run:
    workflows: ["check"]
    branches: [main]
    types:
      - completed

jobs:
  push-store-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './demo-app'
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/yenlianglai/demo-app:latest
          docker push ghcr.io/yenlianglai/demo-app:latest
